chore: Update script -source-gitcheck
Signed-off-by: Rashed Kamal <rashed.kamal@broadcom.com>

diff --git a/tasks/source-git-check.yaml b/tasks/source-git-check.yaml
--- a/tasks/source-git-check.yaml
+++ b/tasks/source-git-check.yaml
@@ -60,7 +60,7 @@ spec:
               exit 1
             fi
 
-            printf "$url" | tr -d '\n' | tee $(results.url.path)
+            echo "$url" | tee $(results.url.path)
 
             if [ ! -z "$branch" ]; then
               sha=$(git ls-remote --heads $url $branch | awk '{print $1}')
@@ -68,16 +68,32 @@ spec:
                 echo "\nerror using git-branch: $(params.git-branch)" | tee $(results.message.path)
                 exit 1
               else
-                echo $sha | tr -d '\n' | tee $(results.sha.path)
-                printf "using git-branch: $(params.git-branch)" | tee $(results.message.path)
+                echo $sha | tee $(results.sha.path)
+                echo "\nsuccess using git-branch: $(params.git-branch)" | tee $(results.message.path)
               fi
             elif [ ! -z "$tag" ]; then
-              git ls-remote --tags $(params.git-url) refs/tags/$(params.git-tag) | awk '{print $1}' | tr -d '\n' | tee $(results.sha.path)
-              printf "using git-tag: $(params.git-tag)" | tee $(results.message.path)
+              sha=$(git ls-remote --tags $(params.git-url) refs/tags/$(params.git-tag) | awk '{print $1}')
+              if [ -z "$sha" ]; then
+                echo "error using git-tag: $(params.git-tag)\n" | tee $(results.message.path)
+                exit 1
+              else
+                echo $sha | tee $(results.sha.path)
+                echo "using git-tag: $(params.git-tag)\n" | tee $(results.message.path)
+              fi
             elif [ ! -z "$commit" ]; then
-              printf "$(params.git-commit)" | tee $(results.sha.path)
-              printf "using git-commit: $(params.git-commit)" | tee $(results.message.path)
+              git_ls_remote_output=$(git ls-remote --refs $(params.git-url) | awk '{print $1}')
+              if [ $? -ne 0 ]; then
+                echo "error: inavlid $(params.git-url)"  | tee $(results.message.path)
+                exit 1
+              fi
+              if echo "$git_ls_remote_output" | grep -q "$commit"; then
+                echo "$(params.git-commit)" | tee $(results.sha.path)
+                echo "using git-commit: $(params.git-commit)\n" | tee $(results.message.path)
+              else
+                echo "error: commit $(params.git-commit)not found in $(params.git-url)\n"  | tee $(results.message.path)
+                exit 1
+              fi
             else
-              printf "Cannot look for source, you must provide one of git-branch, git-tag, git-commit or git-url." | tee $(results.message.path)
+              echo "Cannot look for source, you must provide one of git-branch, git-tag, git-commit or git-url.\n" | tee $(results.message.path)
               exit 1
             fi
